kumuluzee:
  name: code-users
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8085
    http:
      port: 8085
  datasources:
    - jndi-name: jdbc/UserMetadataPS
      connection-url: jdbc:postgresql://localhost:5435/code-users
      username: dbuser
      password: postgres
      max-pool-size: 20
  discovery:
    etcd:
      hosts: http://localhost:2379
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/UserMetadataPS
  metrics:
    web-instrumentation:
      - name: users-endpoint
        url-pattern: /v1/users/*
  security:
    keycloak:
      json: '{
        "realm": "users-realm",
        "bearer-only": true,
        "auth-server-url": "http://localhost:8080/auth/",
        "ssl-required": "external",
        "resource": "users-api",
        "confidential-port": 0
      }'