kumuluzee:
  name: code-users
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8085
    http:
      port: 8085
  datasources:
    - jndi-name: jdbc/UserMetadataPS
      connection-url: jdbc:postgresql://localhost:5435/code-users
      username: dbuser
      password: postgres
      max-pool-size: 20
  discovery:
    etcd:
      hosts: http://localhost:2379
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/UserMetadataPS
  metrics:
    web-instrumentation:
      - name: users-endpoint
        url-pattern: /v1/users/*
  security:
    keycloak:
      json: '{
        "realm": "users-realm",
        "bearer-only": true,
        "auth-server-url": "http://localhost:8080/auth/",
        "ssl-required": "external",
        "resource": "users-api",
        "confidential-port": 0
      }'
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                        <Configuration name="comments">
                            <Appenders>
                                <Console name="console" target="SYSTEM_OUT">
                                    <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                </Console>
                                <Socket name="logstash" host="7d264c39-0e8a-4a2b-b850-db059d5fdb1b-ls.logit.io"
                                port="11963" protocol="tcp">
                                    <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                </Socket>
                            </Appenders>
                            <Loggers>
                                <!-- Default logger -->
                                <Root level="all">
                                    <AppenderRef ref="console" level="info"/>
                                    <AppenderRef ref="logstash" level="trace"/>
                                </Root>
                            </Loggers>
                        </Configuration>'